Ground/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home import views
from django.contrib.auth import views as auth_views

admin.site.site_header='Ground Admin'
admin.site.site_title='Ground Admin'
admin.site.index_title='Ground Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home_url"),
    path('privecy/',views.privecy,name="privecy"),
    path('terms_condition/',views.terms_condition,name="terms_condition"),
    path('developer/',views.developer,name="developer"),
    path('blog/',include('blog.urls',namespace='blog')),
    path('feedback/',views.feedback,name='feedback'),
    path('pastebin/',include('pastebin.urls',namespace='pastebin')),
    path('user/',include('users.urls',namespace='users')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    

    path('search/',views.user_search,name='user_search'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="users/passwordReset.html"),
        name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="users/passwordResetSent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="users/passwordResetForm.html"),
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="users/passwordResetDone.html"),
        name="password_reset_complete"),

    path('archive/',include('archive.urls',namespace='archive')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

archive/urls.py
from django.urls import path
from .import views


app_name = "archive"

urlpatterns = [
    path('main/',views.main_or_search,name='main_or_search'),
    path('delete_solution/<pk>/',views.delete_solution,name='delete_solution'),
    path('edit_solution/<pk>/',views.edit_solution,name='edit_solution'),
    path('like_solution/',views.like_comment_solution,name='like_solution')
]

blog/urls.py
from django.urls import path
from .import views

app_name='blog'

urlpatterns = [
    path('main/',views.blog,name="all_blog"),
    path('blog-details/<pk>/',views.blog_details,name="single_blog"),
    path('create_blog/',views.create_blog,name="create_blog"),
    path('delete_blog/<pk>/',views.delete_blog,name='delete_blog'),
    path('update_blog/<pk>/',views.update_blog,name='update_blog'),

    path('delete_comment/<pk>/<postid>/',views.delete_comment,name='delete_comment'),
    path('update_comment/<pk>/<postid>/',views.update_comment,name='update_comment'),

    path('search/',views.blog_search,name='blog_search')
]

pastebin/urls.py
from django.urls import path
from .import views

app_name = 'pastebin'

urlpatterns = [
    path('bin/',views.bin,name='bin_url'),
    path('show/',views.show,name='show_url'),
    path('bin/delete/<int:id>/',views.delete,name='delete_url'),
    path('bin/update/<int:up_id>/',views.update_post,name='update_url'),
    path('sharedCode/<str:rand_url>/',views.show,name='sharedCode'),
    path('poster_details/<pk>/',views.poster_details,name='poster_details'),
]

posts/urls.py
from django.urls import path
from .import views

app_name = 'posts'

urlpatterns = [
    path('allposts/',views.list_all_post_comments,name='allposts'),
    path('like/',views.like_comment_post,name='postsLike'),
    path('unlike/',views.Unlike_comment_post,name='postsUnlike'),
    path('delete/<pk>/',views.PostDelete,name='postsDelete'),
    path('update/<pk>/',views.PostUpdate,name='postsUpdate'),
    path('details/<pk>',views.PostDetails,name='postsDetails'),
    path('delete/<pk>/<postid>/',views.commentDelete,name='commentDelete'),
    path('edit/<pk>/<postid>/',views.commentEdit,name='commentEdit'), 
    path('search/',views.search_post,name='search_post'),  
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'users'

urlpatterns =[
    path('profile/<profileId>/',views.profile,name='profile'),
    path('signup/',views.signup,name='signup'),
    # path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('changepass',views.changepass,name='changepass'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),

    # path('reset_password/',
    #     auth_views.PasswordResetView.as_view(),
    #     name="reset_password"),

    # path('reset_password_sent/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done"),

    # path('reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm"),

    # path('reset_password_complete/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete"),
]

home/models.py
from django.db import models
from users.models import Profile
# Create your models here.
class Feedback(models.Model):
    content = models.TextField(max_length=300,blank=False)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.content[:20])

    class Meta:
        ordering = ('-created',)

home/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['content',]
        labels = {
            'content':'Feedback',
        }
        widgets = {
            'content':forms.Textarea(attrs={'class':'form-control','placeholder':'Type here your valuable feedback'}),
        }

home/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib.auth import authenticate,login,logout
# from posts.models import Post,Comment
# from django.urls import reverse
from .models import Feedback
from .forms import FeedbackForm
from users.models import Profile
from django.contrib.auth.models import User
from django.db.models import Q
from blog.models import Blog
# Create your views here.


def home(request):
    if request.user.is_authenticated:
        return redirect('posts:allposts')
    else:
        obj = Feedback.objects.all()[:4]
        recent_blogs = Blog.objects.all()[:3]
        context = {
            'feedbacks':obj,
            'recent_blogs':recent_blogs,
            'active':'active',
        }
        return render(request,'home/home.html',context)


def user_search(request):
    query = request.GET['query']
    min_length = True
    if len(query) > 50 :
        min_length = False
        all_user = User.objects.none()
    else:
        all_user = User.objects.filter(Q(id__icontains=query)|Q(username__icontains=query))
    context = {
        'all_user':all_user,
        'min_length':min_length,
        'query':query,
    }
    return render(request,'home/search_user.html',context)




def feedback(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            feedbackObj=FeedbackForm(request.POST)
            profile = Profile.objects.get(user=request.user)
            if feedbackObj.is_valid():
                instance=feedbackObj.save(commit=False)
                instance.author = profile
                instance.save()
                return redirect('home_url')
        else:
            return redirect('users:login')

    else:
        obj = FeedbackForm()
        feedbacks = Feedback.objects.all()
        context = {
            'form':obj,
            'feedbacks':feedbacks,
        }
        return render(request,'home/feedback.html',context)


def privecy(request):
    return render(request,'home/privecy.html')

def terms_condition(request):
    return render(request,'home/terms_condition.html')


def developer(request):
    return render(request,'home/developer.html')

home/templates/home/developer.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<!-- Developer Area -->
<section class="about-dev-area ptb-50">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="dev-img">
                    <img src="../../static/basic/images/dev1.png" alt="dev">
                </div>
            </div>
            <div class="col-lg-7">
                <div class="content">
                    <h2>Akash Karmokar</h2>
                    <span style="color: tomato;">Software Engineer</span>
                    <p>
                        I'm a software engineer specialised in frontend and backend development for complex scalable web apps. I write about software development on my <a href="https://medium.com/@akashcsemu">blog.</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-7">
                <div class="content">
                    <h2>Atikul Islam Atik</h2>
                    <span style="color: tomato;">Former Software Developer at Yo Tech</span>
                    <p>
                        I'm a software developer specialised in frontend and backend development for complex scalable web apps.Love to play with coding.
                    </p>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="dev-img">
                    <img src="../../static/basic/images/dev2.png" alt="dev">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Developer Area -->

{% endblock content %}

home/templates/home/error.html
{% extends 'home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-banner-area ">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12 text-center">
                        <div class="banner-tittle">
                            <h1>
                                Ground
                            </h1>
                        </div>
                        <ul class="head-list">
                            <li>
                                <a href="/">
                                    Home
                                </a>
                            </li>
                            <li>Error</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Start Blog Details Area -->
    <h1>Something is wrong</h1>
<!-- End Blog Details Area -->
{% endblock content %}

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Banner Area -->
<div class="banner-area">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="banner-content">
                            <h1>
                                Share & grow the world's knowledge!
                            </h1>
                            <p>
                                We want to connect the people who have knowledge to the people who need it, to bring
                                together people with different perspectives so they can understand each other better,
                                and to empower everyone to share their knowledge.
                            </p>
                            <div class="banner-btn">
                                <a href="#" class="box-btn">Ask Question</a>
                                <a href="#" class="box-btn border-btn">Share Code</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="banner-img">
                            <img src="../../static/basic/images/banner.png" alt="banner-img" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="home-shape">
        <div class="shape1">
            <img src="../../static/basic/images/2.png" alt="shape">
        </div>
        <div class="shape2">
            <img src="../../static/basic/images/4.png" alt="shape">
        </div>
        <div class="shape3">
            <img src="../../static/basic/images/5.png" alt="shape">
        </div>
        <div class="shape4">
            <img src="../../static/basic/images/3.png" alt="shape">
        </div>

    </div>
</div>
<!-- End Banner Area -->

<!-- Service Area -->
<section class="home-service-area pt-100 pb-70">
    <div class="container">
        <div class="section-title">
            <span>Smart Services</span>
            <h2>Ground Provide All Kind of Solutions</h2>
            <p> We help you get answers to your toughest coding questions, share knowledge with your by others.</p>
        </div>

        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <div class="single-service">
                    <div class="service-img">
                        <img src="../../static/basic/images/services/1.png" alt="service" />
                    </div>

                    <div class="service-content">
                        <h3>Share Problems</h3>
                        <p>Get answers to your questions and give back by sharing your knowledge with others. Sign up
                            for an account.</p>

                        <a href="/" class="line-bnt">
                            Read More
                        </a>
                    </div>
                    <span></span>
                </div>
            </div>

            <div class="col-lg-4 col-sm-6">
                <div class="single-service">
                    <div class="service-img">
                        <img src="../../static/basic/images/services/2.png" alt="service" />
                    </div>

                    <div class="service-content">
                        <h3>Get Answers</h3>
                        <p>Get answers to your questions and give back by sharing your knowledge with others. Sign up
                            for an account.</p>

                        <a href="/" class="line-bnt">
                            Read More
                        </a>
                    </div>
                    <span></span>
                </div>
            </div>

            <div class="col-lg-4 col-sm-6">
                <div class="single-service">
                    <div class="service-img">
                        <img src="../../static/basic/images/services/3.png" alt="service" />
                    </div>

                    <div class="service-content">
                        <h3>Share Code</h3>
                        <p>Write or copy code, then share it with friends and colleagues. Pair program and troubleshoot
                            together.</p>

                        <a href="/" class="line-bnt">
                            Read More
                        </a>
                    </div>
                    <span></span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Service Area -->

<!-- Company Area -->
<section class="home-company-area bg-color" id="home-company">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-12">
                <div class="company-content">
                    <div class="company-tittle">
                        <span>About Us</span>
                        <h2>Innovative It Helping Service All Over the World</h2>

                        <p>We know that all competitive programmers and problem solver sometimes face some obstacles
                            to solve a contest problem’s or any online judges problems. Sometimes they become helpless
                            to solve a problem. Then they search problems solution in internet or in those online judge
                            platform. Though present days online judge has tutorial site , but many online judge are in
                            internet which has no tutorial site or problems solutions code . Besides this , sometimes
                            coder’s face problem to share code with other’s. If we share this code with the help of
                            social
                            media , that doesn’t follow code indentation .</p>

                        <p>So we are develop a web based
                            application which have code share option, post option to get help from other and online
                            judge’s
                            problems solved code link.</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="company-img">
                    <img src="../../static/basic/images/about.png" alt="about" />
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Company Area -->

<!-- Start Review Area -->
<section class="home-review-area">
    <div class="container">
        <div class="row">
            <div class="review-area">
                <div class="review-tittle">
                    <span>Feedback</span>
                    <h2>What Our User's Say</h2>
                </div>
                <div class="container">
                    <div class="review-slider owl-carousel owl-theme">
                        {% for feedback in feedbacks %}
                        <div class="single-slider">
                            <div class="testimonial-item">
                                <div class="review-img">
                                    <img src="{{feedback.author.avater.url}}" alt="review-img">
                                </div>
                                <div class="review-content">
                                    <p><i class='bx bxs-quote-alt-left'></i>{{feedback.content|slice:300}}<i
                                            class='bx bxs-quote-alt-right'></i></p>
                                    <h5>{{feedback.author.user}}</h5>
                                    <span>Developer</span>
                                </div>
                                <div class="shape">
                                    <img src="../../static/basic/images/tshape.png" alt="shape">
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Review Area -->

<!-- Blog Area -->
<section class="home-blog-area">
    <div class="container">
        <div class="section-title">
            <span>Blog Post</span>
            <h2>Our Regular Blogs</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A facilis vel consequatur tempora atque
                blanditiis exercitationem incidunt, alias corporis quam assumenda dicta.</p>
        </div>

        <div class="row">
            {% for recent in recent_blogs %}
            <div class="col-lg-4 col-md-6">
                <div class="single-blog">
                    <div class="content">
                        <a href="{% url 'blog:single_blog' recent.id %}">
                            <h3>{{recent.title|slice:50}}</h3>
                        </a>
                        <ul>
                            <li>
                                <span>On:{{recent.created|date}}</span>
                            </li>
                            <li>
                                <a href=""><span>By {{recent.author.user}}</span></a>
                            </li>

                        </ul>

                        <ul class="mt-2">
                            <li>
                                <span><i class="bx bx-low-vision"></i>{{recent.read.all.count}} views</span>
                            </li>
                            <li>
                                <span><i class="bx bx-comment"></i>{{recent.num_comments}} comments</span>
                            </li>
                        </ul>

                        <span class="catagory">{{recent.category}}</span>
                        <a href="{% url 'blog:single_blog' recent.id %}" class="box-btn mt-4">Read More</a>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
        <div class="blog-btn text-center">
            <p>We Have More Usefull Blogs For You. <a href="{% url 'blog:all_blog' %}">View More</a></p>
        </div>
    </div>
</section>
<!-- End Blog Area -->

<!-- Footer Area -->
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="content">
                    <div class="logo">
                        <a href="/"> <img src="../../static/basic/images/logo2.png" alt="logo"></a>
                    </div>
                    <p>
                        Ground is a social questions & Answers Engine which will help you establis your community and
                        connect with other people.
                    </p>

                    <ul class="social">
                        <li>
                            <a href="#" target="_blank"><i class='bx bxl-facebook'></i></a>
                        </li>
                        <li>
                            <a href="#" target="_blank"><i class='bx bxl-twitter'></i></a>
                        </li>
                        <li>
                            <a href="#" target="_blank"><i class='bx bxl-instagram'></i></a>
                        </li>
                        <li>
                            <a href="#" target="_blank"><i class='bx bxl-pinterest'></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="content ml-15">
                    <h3>Our Service</h3>
                    <ul class="footer-list">
                        <li><a href="#">Pastebin</a></li>
                        <li><a href="#"> Blog</a></li>
                        <li><a href="#">Post</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6">
                <div class="content">
                    <h3>Quick Links</h3>
                    <ul class="footer-list">
                        <li><a href="#home-company">Service</a></li>
                        <li><a href="privecy.html">Privacy & Policy</a></li>
                        <li><a href="terms-condition.html">Terms & Conditions</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="content contacts">
                    <h3 class="ml-40">Contact</h3>
                    <ul class="footer-list foot-social">
                        <li><a href="tel:+1975456789"><i class="bx bx-phone"></i> +1 975 456 789</a></li>
                        <li><a href="mailto:ground.mu@gmail.com"><i class="bx bxs-envelope"></i>ground.mu@gmail.com</a>
                        </li>
                        <li><i class="bx bxs-map"></i> Sylhet, Bangladesh</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="lines">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
    </div>
    <div class="copy-area">
        <p class="text-center">
            Copyright &copy; 2020 Ground. All Rights Reserved.
        </p>
    </div>
</footer>
<!-- End Footer Area -->

{% endblock content %}

home/templates/home/navbar.html
<!--Navbar Area -->
<div class="navbar-area">
   <div class="mobile-nav">
      <a href="index.html" class="logo">
         GROUND
      </a>
   </div>
   <div class="main-nav">
      <div class="container">
         <nav class="navbar navbar-expand-md navbar-light">
            <a class="navbar-brand" href="/">
              GROUND
            </a>
            <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
               {% with url_name=request.resolver_match.url_name %}
               <ul class="navbar-nav m-auto">
                  <li class="nav-item {% if url_name == 'home_url' %}{{active}}{% endif %}">
                     <a href="{% url 'home_url' %}" class="nav-link">Home</a>
                  </li>
                  <li class="nav-item {% if url_name == 'allposts' %}{{active}}{% endif %}">
                     <a href="{% url 'posts:allposts' %}" class="nav-link">Posts</a>
                  </li>
                  <li class="nav-item {% if url_name == 'bin_url' %}{{active}}{% endif %}">
                     <a class="nav-link" href="{% url 'pastebin:bin_url' %}">Pastebin</a>
                  </li>
                  <li class="nav-item {% if url_name == 'main_or_search' %}{{active}}{% endif %}">
                     <a href="{% url 'archive:main_or_search' %}" class="nav-link ">Archive</a>
                  </li>
                  <li class="nav-item {% if url_name == 'all_blog' %}{{active}}{% endif %}">
                     <a class="nav-link" href="{% url 'blog:all_blog' %}">Blog</a>
                  </li>
               </ul>
               {% endwith %}
            </div>

            <ul class="navbar-nav mr-auto align-items-center">
               <li class="nav-item">
                  <div class='search-box'>
                     <form class="search-form" method='GET' action="{% url 'user_search' %}">
                        <input class="form-control" type="search" placeholder="User Id or Username" aria-label="Search"
                           name="query" id="query">
                        <button class="search-button" type="submit">
                           <i class="search-btn bx bx-search"></i>
                        </button>
                     </form>
                  </div>
               </li>

               {% if request.user.is_authenticated %}
               <li class="nav-item">
                  <a href="{% url 'users:profile' request.user.profile.id %}" class="nav-link dropdown-toggle"><img
                        class="nav-profile-img" src="{{request.user.profile.avater.url}}" alt="profile"> {{user}} </a>
                  <ul class="dropdown-menu">
                     <li class="nav-item">
                        <a href="{% url 'users:profile' request.user.profile.id  %}" class="nav-link">Profile</a>
                     </li>
                     <li class="nav-item">
                        <a href="{% url 'users:changepass' %}" class="nav-link">Change Password</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'feedback' %}">Feedback</a>
                     </li>
                     <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link">Logout</a>
                     </li>
                  </ul>
               </li>
               {% else %}
               <li class="nav-item {% if url_name == 'signup' %}{{active}}{% endif %}">
                  <a href="{% url 'users:signup' %}" class="nav-link">Sign Up</a>
               </li>
               <li class="nav-item {% if url_name == 'login' %}{{active}}{% endif %}">
                  <a href="{% url 'users:login' %}" class="nav-link">Sign In</a>
               </li>
               {% endif %}
            </ul>
         </nav>
      </div>
   </div>
</div>
<!-- End Navbar Area -->

home/templates/home/privecy.html
<h2>dsd</h2>

home/templates/home/profile.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    <h1>Profile Page</h1>
{% endblock content %}

home/templates/home/search_user.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<section class="main-review-area ptb-50">
    <div class="container">
        <div class="tab quote-list-tab">
            <ul class="tabs">
                <li>
                    <a href="#">
                        Searach Result
                    </a>
                </li>
            </ul>
            <div class="row">
                <div class="col-lg-12">

                    {% if not min_length %}
                        <div class="col-lg-12">
                              <p>Your search-</p>
                              <h4>{{query|slice:'10'}}..........</h4>
                              <p>did not match any documents</p> 
                              <h5>Suggestions:</h5>
                              <ol>
                                <li>Make sure that all words are spelled correctly</li>
                                <li>Try different keywords</li>
                                <li>Try more general keywords</li>
                                <li>Try fewer keywords</li>
                              </ol>
                        </div>
                    {% else %}
                        {% if all_user.count == 0 %}
                            <div class="col-lg-12">
                                <p>No search result found.Please refine your query</p>
                            </div>
                        {% else %}
                            {% for user in all_user %}
                                <div class="col-lg-12">
                                    <div class="single-reviews">
                                        <div class="content d-flex align-items-center">
                                            <div class="review-img">
                                                <img src="{{user.profile.avater.url}}" alt="demo">
                                            </div>
                                            <a href="{% url 'users:profile' user.id %}">{{user}}</a>
                                            <span>{{user.profile.created}}</span>
                                        </div>
                                        <p>{{user.profile.bio}}</p>
                                    </div>
                                    <hr>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% include "home/footer.html" %}
<button></button>

home/templates/home/terms_condition.html
<h2>s</h2>