Ground/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home import views
from django.contrib.auth import views as auth_views

admin.site.site_header='Ground Admin'
admin.site.site_title='Ground Admin'
admin.site.index_title='Ground Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home_url"),
    path('privecy/',views.privecy,name="privecy"),
    path('terms_condition/',views.terms_condition,name="terms_condition"),
    path('developer/',views.developer,name="developer"),
    path('blog/',include('blog.urls',namespace='blog')),
    path('feedback/',views.feedback,name='feedback'),
    path('pastebin/',include('pastebin.urls',namespace='pastebin')),
    path('user/',include('users.urls',namespace='users')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    

    path('search/',views.user_search,name='user_search'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="users/passwordReset.html"),
        name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="users/passwordResetSent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="users/passwordResetForm.html"),
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="users/passwordResetDone.html"),
        name="password_reset_complete"),

    path('archive/',include('archive.urls',namespace='archive')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

archive/urls.py
from django.urls import path
from .import views


app_name = "archive"

urlpatterns = [
    path('main/',views.main_or_search,name='main_or_search'),
    path('delete_solution/<pk>/',views.delete_solution,name='delete_solution'),
    path('edit_solution/<pk>/',views.edit_solution,name='edit_solution'),
    path('like_solution/',views.like_comment_solution,name='like_solution')
]

blog/urls.py
from django.urls import path
from .import views

app_name='blog'

urlpatterns = [
    path('main/',views.blog,name="all_blog"),
    path('blog-details/<pk>/',views.blog_details,name="single_blog"),
    path('create_blog/',views.create_blog,name="create_blog"),
    path('delete_blog/<pk>/',views.delete_blog,name='delete_blog'),
    path('update_blog/<pk>/',views.update_blog,name='update_blog'),

    path('delete_comment/<pk>/<postid>/',views.delete_comment,name='delete_comment'),
    path('update_comment/<pk>/<postid>/',views.update_comment,name='update_comment'),

    path('search/',views.blog_search,name='blog_search')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'users'

urlpatterns =[
    path('profile/<profileId>/',views.profile,name='profile'),
    path('signup/',views.signup,name='signup'),
    # path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('changepass',views.changepass,name='changepass'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),

    # path('reset_password/',
    #     auth_views.PasswordResetView.as_view(),
    #     name="reset_password"),

    # path('reset_password_sent/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done"),

    # path('reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm"),

    # path('reset_password_complete/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete"),
]

archive/models.py
from django.db import models
from users.models import Profile


# Create your models here.

class Domain(models.Model):
    name = models.CharField(max_length=50)
    updated = models.DateTimeField(auto_now=True) 
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    
class Solution(models.Model):
    domain = models.ForeignKey(Domain,on_delete=models.CASCADE)
    number = models.CharField(max_length=50)
    link = models.CharField(max_length=200)
    author = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='solutions')
    like = models.ManyToManyField(Profile,blank=True,related_name='solution_like')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.domain} ----  {self.number}"

    def num_likes(self):
        return self.like.all().count()

    # class Meta:
    #     ordering = ('like.all.count',)



LIKE_CHOICES = {
    ('Like','Like'),
    ('Unlike','Unlike'),
}

class solutionLike(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    solution = models.ForeignKey(Solution,on_delete=models.CASCADE)
    value = models.CharField(max_length=10,choices=LIKE_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}--{self.solution}--{self.value}"
    

archive/forms.py
from django import forms
from .models import Domain,Solution



class DomainModelForm(forms.ModelForm):
    name = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control','rows':'1','placeholder':'Create domain'}))
    class Meta:
        model = Domain
        fields = ['name',]


class SolutionModelForm(forms.ModelForm):
    number = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control','rows':'1','placeholder':'Type Problem Number'}))
    link = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control','rows':'1','placeholder':'Paste Link Here'}))
    class Meta:
        model = Solution
        fields = ['domain','number','link',]

archive/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from .models import Solution,solutionLike,Domain
from .forms import SolutionModelForm,DomainModelForm
from django.db.models import Q
from users.models import Profile
from django.urls import reverse



# Create your views here.
def main_or_search(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            if 'create_solution_form' in request.POST:
                profile = Profile.objects.get(user=request.user)
                solution_form = SolutionModelForm(request.POST or None)
                if solution_form.is_valid():
                    instance = solution_form.save(commit=False)
                    instance.author = profile
                    instance.save()
                    return redirect('archive:main_or_search')

            if 'create_domain_form' in request.POST:
                profile = Profile.objects.get(user=request.user)
                domain_form = DomainModelForm(request.POST or None)
                if domain_form.is_valid():
                    instance = domain_form.save(commit=False)
                    # instance.author = profile
                    instance.save()
                    return redirect('archive:main_or_search')
        else:
            return redirect('users:login')
    else:
        if 'domain' in request.GET or 'num' in request.GET:
            # print("//////")
            domain_query = request.GET['domain']
            number_query = request.GET['num']
            solutions = Solution.objects.filter(Q(domain=domain_query) | Q(number=number_query))
            domains = Domain.objects.all()
            # print(domains)
            solution_form = SolutionModelForm()
            domain_form = DomainModelForm()
            context = {
                'solutions':solutions,
                'domains':domains,
                'solution_form':solution_form,
                'domain_form':domain_form,
                'search_flag':True,
            }
            return render(request,'archive/main.html',context)
        else:
            # print("xxxxxxxxxx")
            solutions = Solution.objects.all()
            domains = Domain.objects.all()
            # print(domains)
            solution_form = SolutionModelForm()
            domain_form = DomainModelForm()
            context = {
                'solutions':solutions,
                'domains':domains,
                'solution_form':solution_form,
                'domain_form':domain_form,
            }
            return render(request,'archive/main.html',context)


def delete_solution(request,pk):
    if request.user.is_authenticated:
        try:
            obj = Solution.objects.get(pk=pk)
            if obj.author.user == request.user:
                obj.delete()
                return redirect(request.META['HTTP_REFERER'])
            else:
                return render(request,'home/error.html')
        except Solution.DoesNotExist:
            return render(request,'home/error.html')
    else:
        return redirect('users:login')


def edit_solution(request,pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            obj = Solution.objects.get(pk=pk)
            if obj.author.user == request.user:
                if 'domain_submit_form' in request.POST:
                    domain_form = DomainModelForm(request.POST or None)
                    if domain_form.is_valid():
                        domain_form.save()
                        return redirect(request.META['HTTP_REFERER'])
                solution_form = SolutionModelForm(request.POST or None,instance=obj)
                if solution_form.is_valid():
                    solution_form.save()
                    return redirect('archive:main_or_search')
            else:
                return render(request,'home/error.html')
        else:
            try:
                obj = Solution.objects.get(pk=pk)
                if obj.author.user == request.user:
                    solution_form = SolutionModelForm(instance=obj)
                    domain_form = DomainModelForm()

                    context={
                        'solution_form':solution_form,
                        'domain_form':domain_form,
                    }
                    return render(request,'archive/edit_solution.html',context)

                else:
                    return render(request,'home/error.html')
            except Solution.DoesNotExist:
                return render(request,'home/error.html') 
    else:
        return redirect('users:login')
    # return render(request,'archive/edit_solution.html')
    


def like_comment_solution(request):
    if request.user.is_authenticated:
        currentUser = request.user
        if request.method == 'POST':
            solution_id = request.POST.get('solution_id')
            solutionObj = Solution.objects.get(id=solution_id)
            profileObj = Profile.objects.get(user=currentUser)

            if profileObj in solutionObj.like.all():
                solutionObj.like.remove(profileObj)
            else:
                solutionObj.like.add(profileObj)

            like, created = solutionLike.objects.get_or_create(user=profileObj,solution_id=solution_id)
            if not created:
                if like.value == 'Like':
                    like.value = 'Unlike'
                else:
                    like.value = 'Like'
            else:
                like.value = 'Like'
                
                solutionObj.save()
                like.save()
        return redirect('archive:main_or_search')
    
    else:
        return HttpResponseRedirect('/user/login/')

archive/templates/archive/edit_solution.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<div class="post-details-area">
    <div class="post-banner-area ">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="banner-tittle">
                                <h1>
                                    Archive
                                </h1>
                            </div>
                            <ul class="head-list">
                                <li>
                                    <a href="/">
                                        Home
                                    </a>
                                </li>
                                <li>Edit Your Solution</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Blog Create Area -->

<div class="blog-create">
    <div class="container">
        <h2 class="text-center mt-5">Edit Your Solution</h2>
        <div class="row">
            <div class="col-lg-10 offset-lg-1 text-center mt-5">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% comment %} {{blog_create_form.as_p}} {% endcomment %}
                    {% for fm in solution_form %}
                        {{fm}}
                        {% ifequal fm.label|lower 'domain' %}
                            <button type="button" class="edit-btn box-btn" data-toggle="modal" data-target="#addDomain">
                                <i class='bx bx-plus'></i>
                            </button>
                        {% endifequal %}
                    {% endfor %}
                    <button type="submit" class="box-btn mt-4 mb-5 blog" name="solution_update_form">Update</button>
                </form>
            </div>
        </div>

        <!--Modal-->
                <div class="modal fade" id="addDomain" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                    aria-hidden="true">
                    <div class="modal-md modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3>Category</h3>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {% comment %} {{form|crispy}} {% endcomment %}
                                        {{domain_form}}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="box-btn" name="domain_submit_form">Add Category</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>


    </div>
</div>

{% include "home/footer.html" %} 

{% endblock content %}

archive/templates/archive/main.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<div class="post-details-area">
    <div class="post-banner-area ">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="banner-tittle">
                                <h1>
                                    Archive
                                </h1>
                            </div>
                            <ul class="head-list">
                                <li>
                                    <a href="/">
                                        Home
                                    </a>
                                </li>
                                <li>Archive</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="archive-area ptb-50m">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="archive-post-area">
                    <div class="archive-accordion">
                        <ul class="accordion">
                            <li class="accordion-item">
                                <a class="accordion-title active" href="javascript:void(0)">
                                    <i class="bx bx-plus"></i> Stocks Your Solutions
                                </a>
                                <div class="accordion-content">
                                    <form action="" method="POST">
                                        <label>Select a Domain</label>
                                        {% csrf_token %}
                                        {% for form in solution_form %}
                                            {{form}}
                                            {% ifequal  form.label|lower 'domain' %}
                                                <fieldset class="question">
                                                    <label for="add_cata">Do you have another Doamin.?</label>
                                                    <input class="add_cata" type="checkbox" name="coupon_question" value="1" />
                                                    <span class="item-text">Yes</span>
                                                    <button type="button" class="btn btn-primary answer" data-toggle="modal"
                                                    data-target="#createArchive"><i class='bx bx-plus'></i></button>
                                                </fieldset>
                                            {% endifequal %}
                                        {% endfor %}
                                        <button type="submit" class="btn btn-success" name="create_solution_form">Create</button>
                                    </form>
                                </div>
                            </li>
                            <li class="accordion-item">
                                <a class="accordion-title" href="javascript:void(0)">
                                    <i class="bx bx-plus"></i>Find Your Solutions
                                </a>
                                <div class="accordion-content">
                                    <form method="GET" action="{% url 'archive:main_or_search' %}">
                                        <div class="form-row">
                                            <div class="col-12 mb-3">
                                                {% comment %} <input type="text" class="form-control" placeholder="Domain" name="domain"
                                                    id="domain"> {% endcomment %}
                                                <label>Select a Domain for Filter</label>
                                                <select name="domain" id="domain" class="form-control">
                                                    {% for domain in domains %}
                                                    <option value="{{domain.id}}">{{domain.name}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <div class="col-12 mb-3">
                                                <input type="text" class="form-control" placeholder="Problem Link" name="num" id="num">
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </form>
                                </div>
                            </li>
                        </ul>
                    </div
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="table-responsive" style="margin-bottom: 50px;">
                {% if search_flag %}
                    <a href="{% url 'archive:main_or_search' %}">Reset</a>
                {% endif %}
                {% if solutions %}
                    <table class="table">
                        <thead class="" style="background-color: #051242; color:#fff; line-height:3;">
                            <tr style="border-bottom: 1px solid #ecec;">
                                <th scope="col">Domain</th>
                                <th scope="col">Problem Number</th>
                                <th scope="col">Solution Link</th>
                                <th scope="col">Author</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for solution in solutions %}
                            <tr>
                                <td>{{solution.domain}} </td>
                                <td class="problem-number">{{solution.number}} </td>
                                <td class="problem-link"><a href="{{solution.link}}" target="_blank">{{solution.link}} </a></td>
                                <td><a href="{% url 'users:profile' solution.author.id %}">{{solution.author.user}}</a></td>
                                <td>
                                    {% if solution.author.user == request.user %}
                                        <a href="{% url 'archive:delete_solution' solution.id %}">Delete</a>
                                        <a href="{% url 'archive:edit_solution' solution.id %}">Edit</a>
                                    {% else %}
                                        <form action="{% url 'archive:like_solution' %}" id='{{solution.id}}' method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="solution_id" value={{solution.id}}>
                                            <button class="btn btn-success">Like({{solution.num_likes}})</button>
                                        </form>
                                        {% comment %} <a href="" data-toggle="modal" data-target="#likes">See All</a> {% endcomment %}
                                        <!--Modal-->
                                        <div class="modal fade" id="likes" tabindex="-1" role="dialog"
                                            aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                            <div class="modal-md modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h3>People who likes solution</h3>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary"
                                                                data-dismiss="modal">Close</button>
                                                            {% comment %} <button type="submit" class="box-btn" name="category_submit_form">Add
                                                                Category</button> {% endcomment %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div>
                        <h2 style="color:tomato">No results found</h2>
                    </div>
                {% endif %}
                {% comment %} <table class="table">
                    <thead class="" style="background-color: #051242; color:#fff; line-height:3;">
                        <tr style="border-bottom: 1px solid #ecec;">
                            <th scope="col">Domain</th>
                            <th scope="col">Problem Number</th>
                            <th scope="col">Solution Link</th>
                            <th scope="col">Author</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for solution in solutions %}
                        <tr>
                            <td>{{solution.domain}} </td>
                            <td class="problem-number">{{solution.number}} </td>
                            <td class="problem-link"><a href="{{solution.link}}" target="_blank">{{solution.link}} </a></td>
                            <td><a href="{% url 'users:profile' solution.author.id %}">{{solution.author.user}}</a></td>
                            <td>
                                {% if solution.author.user == request.user %}
                                    <a href="{% url 'archive:delete_solution' solution.id %}">Delete</a>
                                    <a href="{% url 'archive:edit_solution' solution.id %}">Edit</a>
                                {% else %}
                                    <form action="{% url 'archive:like_solution' %}" id='{{solution.id}}' method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="solution_id" value={{solution.id}}>
                                        <button>Like({{solution.num_likes}})</button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table> {% endcomment %}
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="createArchive" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for form in domain_form %}
                        {{form}}
                        {% endfor %}
                        <button type="button" class="btn btn-secondary mt-4" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success mt-4" name="create_domain_form">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% include "home/footer.html" %} 

{% endblock content %}