Ground/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home import views
from django.contrib.auth import views as auth_views

admin.site.site_header='Ground Admin'
admin.site.site_title='Ground Admin'
admin.site.index_title='Ground Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home_url"),
    path('privecy/',views.privecy,name="privecy"),
    path('terms_condition/',views.terms_condition,name="terms_condition"),
    path('developer/',views.developer,name="developer"),
    path('blog/',include('blog.urls',namespace='blog')),
    path('feedback/',views.feedback,name='feedback'),
    path('pastebin/',include('pastebin.urls',namespace='pastebin')),
    path('user/',include('users.urls',namespace='users')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    

    path('search/',views.user_search,name='user_search'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="users/passwordReset.html"),
        name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="users/passwordResetSent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="users/passwordResetForm.html"),
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="users/passwordResetDone.html"),
        name="password_reset_complete"),

    path('archive/',include('archive.urls',namespace='archive')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from .import views

app_name='blog'

urlpatterns = [
    path('main/',views.blog,name="all_blog"),
    path('blog-details/<pk>/',views.blog_details,name="single_blog"),
    path('create_blog/',views.create_blog,name="create_blog"),
    path('delete_blog/<pk>/',views.delete_blog,name='delete_blog'),
    path('update_blog/<pk>/',views.update_blog,name='update_blog'),

    path('delete_comment/<pk>/<postid>/',views.delete_comment,name='delete_comment'),
    path('update_comment/<pk>/<postid>/',views.update_comment,name='update_comment'),

    path('search/',views.blog_search,name='blog_search')
]

posts/urls.py
from django.urls import path
from .import views

app_name = 'posts'

urlpatterns = [
    path('allposts/',views.list_all_post_comments,name='allposts'),
    path('like/',views.like_comment_post,name='postsLike'),
    path('unlike/',views.Unlike_comment_post,name='postsUnlike'),
    path('delete/<pk>/',views.PostDelete,name='postsDelete'),
    path('update/<pk>/',views.PostUpdate,name='postsUpdate'),
    path('details/<pk>',views.PostDetails,name='postsDetails'),
    path('delete/<pk>/<postid>/',views.commentDelete,name='commentDelete'),
    path('edit/<pk>/<postid>/',views.commentEdit,name='commentEdit'), 
    path('search/',views.search_post,name='search_post'),  
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'users'

urlpatterns =[
    path('profile/<profileId>/',views.profile,name='profile'),
    path('signup/',views.signup,name='signup'),
    # path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('changepass',views.changepass,name='changepass'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),

    # path('reset_password/',
    #     auth_views.PasswordResetView.as_view(),
    #     name="reset_password"),

    # path('reset_password_sent/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done"),

    # path('reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm"),

    # path('reset_password_complete/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete"),
]

blog/models.py
from django.db import models
from users.models import Profile
from ckeditor.fields import RichTextField
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    updated = models.DateTimeField(auto_now=True) 
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    


# Blog Model
class Blog(models.Model):
    title = models.CharField(max_length=250)
    # content = models.TextField()
    content = RichTextField()
    updated = models.DateTimeField(auto_now=True) 
    created = models.DateTimeField(auto_now_add=True)
    read = models.ManyToManyField(Profile,blank=True,related_name='reads')
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='category')
    author = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='blogs')


    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def num_comments(self):
        return self.blogcomment_set.all().count()

    class Meta:
        ordering = ('-created',)


# Comment Model
class blogComment(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


# Like Model
LIKE_CHOICES = {
    ('Read','Read'),
    ('Unread','Unread'),
}

class blogRead(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE)
    value = models.CharField(max_length=10,choices=LIKE_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}--{self.blog}--{self.value}"
    

blog/forms.py
from django import forms
from .models import Blog,blogComment,Category
from ckeditor.fields import RichTextField

class CategoryModelForm(forms.ModelForm):
    name = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Create a new category'}))
    class Meta:
        model = Category
        fields = ['name',]        


class CreateBlogModelForm(forms.ModelForm):
    title = forms.CharField(label='',widget=forms.Textarea(attrs={'class':'form-control heading-form','rows':'1','placeholder':'Title'}))
    
    # category = forms.Select(widget=forms.Select(attrs={'class':'form-control heading-form','rows':'1','placeholder':'sss'}))

    class Meta:
        model = Blog
        fields = ['title','category','content']
        
class blogCommentModalForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class':'form-control'})
    )
    class Meta:
        model = blogComment
        fields = ['body']

blog/views.py
from django.shortcuts import render,redirect
from .models import Blog,blogComment,blogRead
from users.models import Profile
from .forms import CreateBlogModelForm,blogCommentModalForm,CategoryModelForm
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.db.models import Q
from posts.models import Post
# Create your views here.


def blog(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            blog_create_form=CreateBlogModelForm(request.POST or None)
            profile = Profile.objects.get(user=request.user)
            if blog_create_form.is_valid():
                instance = blog_create_form.save(commit=False)
                instance.author = profile
                instance.save()
                CreateBlogModelForm()
                blog_obj=Blog.objects.all()
                blog_create_form = CreateBlogModelForm()
                context = {
                    'blog_obj':blog_obj,
                    'blog_create_form':blog_create_form,
                    'active':'active',
                }
                return render(request,'blog/blog.html',context)
        else:
            return redirect('users:login')
    else:
        blog_obj=Blog.objects.all()
        blog_create_form = CreateBlogModelForm()
        context = {
            'blog_obj':blog_obj,
            'blog_create_form':blog_create_form,
            'active':'active',
        }
    return render(request, 'blog/blog.html',context)

def blog_details(request,pk):
    if request.method == 'POST':
        if request.user.is_authenticated:
            if 'read_more' in request.POST:
                blog_obj = Blog.objects.get(pk=pk)
                comment_form = blogCommentModalForm()
                current_User = request.user
                blog_Id = request.POST.get('read_more')
                profile_obj = Profile.objects.get(user=current_User)

                if profile_obj not in blog_obj.read.all():
                    blog_obj.read.add(profile_obj)

                read, created = blogRead.objects.get_or_create(user=profile_obj,blog_id=blog_Id)
                if created:
                    read.value = 'Read'
                blog_obj.save()
                read.save()

                recent_posts = Post.objects.all()[:10]
                context = {
                    'blog_obj':blog_obj,
                    'recent_posts':recent_posts,
                    'comment_form':comment_form,
                    'active':'active',
                }
                return render(request, 'blog/blog-details.html',context)

            if 'comment_submit_form' in request.POST:
                comment_form = blogCommentModalForm(request.POST or None)
                profile = Profile.objects.get(user=request.user)
                if comment_form.is_valid():
                    instance = comment_form.save(commit=False)
                    instance.user = profile
                    instance.blog = Blog.objects.get(id = request.POST.get('blog_id'))
                    instance.save()
                    blog_obj = Blog.objects.get(pk=pk)
                    comment_form = blogCommentModalForm()
                    context = {
                        'blog_obj':blog_obj,
                        'comment_form':comment_form,
                        'active':'active',
                    }
                    return render(request, 'blog/blog-details.html',context)    
        else:
            return redirect('users:login')
    else:
        blog_obj = Blog.objects.get(pk=pk)
        recent_posts = Post.objects.all()[:10]
        comment_form = blogCommentModalForm()
        context = {
            'blog_obj':blog_obj,
            'recent_posts':recent_posts,
            'comment_form':comment_form,
            'active':'active',
        }
        return render(request, 'blog/blog-details.html',context)    



def create_blog(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            if 'category_submit_form' in request.POST:
                created_category = CategoryModelForm(request.POST or None)
                if created_category.is_valid():
                    created_category.save()
                    return redirect('blog:create_blog')
            if 'blog_submit_form' in request.POST:
                blog_create_form=CreateBlogModelForm(request.POST or None)
                profile = Profile.objects.get(user=request.user)
                if blog_create_form.is_valid():
                    instance = blog_create_form.save(commit=False)
                    instance.author = profile
                    instance.save()
                    CreateBlogModelForm()
                    blog_obj=Blog.objects.all()
                    blog_create_form = CreateBlogModelForm()
                    context = {
                        'blog_obj':blog_obj,
                        'blog_create_form':blog_create_form,
                        'active':'active',
                    }
                    return render(request,'blog/blog.html',context)
        else:
            return redirect('users:login')
    else:
        blog_create_form = CreateBlogModelForm()
        category_form = CategoryModelForm()
        context = {
            'blog_create_form':blog_create_form,
            'category_form':category_form,
            'active':'active',
        }
        return render(request,'blog/createBlog.html',context)


def delete_blog(request,pk):
    if request.user.is_authenticated:
        try:
            obj = Blog.objects.get(pk=pk)
            if obj.author.user == request.user:
                obj.delete()
                return redirect('blog:all_blog')
            else:
                return render(request,'home/error.html') 
        except Blog.DoesNotExist:
            return render(request,'home/error.html') 
    else:
        return redirect('users:login')


def update_blog(request,pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            try:
                obj = Blog.objects.get(pk=pk)
                if obj.author.user == request.user:
                    if 'category_submit_form' in request.POST:
                        created_category = CategoryModelForm(request.POST or None)
                        if created_category.is_valid():
                            created_category.save()
                            return redirect('blog:update_blog')
                    form = CreateBlogModelForm(request.POST,instance=obj)
                    if form.is_valid():
                        form.save()
                        form = CreateBlogModelForm()
                        context = {
                            'form':form,
                        }
                        return redirect(reverse('blog:single_blog',args=pk))
            except Blog.DoesNotExist:
                return render(request,'home/error.html')
        else:
            try:
                obj = Blog.objects.get(pk=pk)
                if obj.author.user == request.user:
                    form = CreateBlogModelForm(instance=obj)
                    category_form = CategoryModelForm()
                    context={
                        'form':form,
                        'category_form':category_form,
                        'active':'active',
                    }
                    return render(request,'blog/updateBlog.html',context)
            except Blog.DoesNotExist:
                return render(request,'home/error.html')
    else:
        return redirect('users:login')


# ////////////////// Comment Section ///////////////////

def delete_comment(request,pk,postid):
    if request.user.is_authenticated:
        print(postid)
        try:
            obj = blogComment.objects.get(pk=pk)
            if obj.user.user == request.user:
                obj.delete()
                return redirect(reverse('blog:single_blog',args=postid))
            else:
                return render(request,'home/error.html')
        except blogComment.DoesNotExist:
            return render(request,'home/error.html')
    else:
        return redirect('users:login')



def update_comment(request,pk,postid):
    if request.user.is_authenticated:
        if request.method == 'POST':
            try:
                obj = blogComment.objects.get(pk=pk)
                if obj.user.user == request.user:
                    form = blogCommentModalForm(request.POST,instance=obj)
                    if form.is_valid():
                        form.save()
                        return redirect(reverse('blog:single_blog',args=postid))
                else:
                    return render(request,'home/error.html')
            except blogComment.DoesNotExist:
                return render(request,'home/error.html') 
        else:
            try:
                obj = blogComment.objects.get(pk=pk)
                if obj.user.user == request.user:
                    form = blogCommentModalForm(instance=obj)
                    context={
                        'form':form,
                        'active':'active',
                    }
                    return render(request,'blog/update_comment.html',context)
            except blogComment.DoesNotExist:
                return render(request,'home/error.html') 
    else:
        return redirect('users:login')





# ///////////////////////////////  Blog Search /////////////////////////////

def blog_search(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            blog_create_form=CreateBlogModelForm(request.POST or None)
            profile = Profile.objects.get(user=request.user)
            if blog_create_form.is_valid():
                instance = blog_create_form.save(commit=False)
                instance.author = profile
                instance.save()
                CreateBlogModelForm()

blog/templates/blog/blog-details.html
{% extends 'home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-banner-area ">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12 text-center">
                        <div class="banner-tittle">
                            <h1>
                                {{blog_obj.title}}
                            </h1>
                        </div>
                        <ul class="head-list">
                            <li>
                                <a href="/">
                                    Home
                                </a>
                            </li>
                            <li>{{blog_obj.title}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Start Blog Details Area -->
<section class="blog-details-area ptb-50m">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="blog-details-desc">
                    <div class="article-content">
                        <div class="entry-meta">
                            <h3>{{blog_obj.title}}</h3>
                            <ul>
                                <li><span>Posted On:</span> <a href="#">{{blog_obj.created}}</a></li>
                                <li><span>Posted By:</span> <a
                                        href="{% url 'users:profile' blog_obj.author.user.id %}">{{blog_obj.author.user}}</a>
                                </li>
                                {% if blog_obj.author.user == request.user %}
                                <li><a href="{% url 'blog:update_blog' blog_obj.id %}"><span>Edit</span></a></li>
                                <li><a href="{% url 'blog:delete_blog' blog_obj.id %}"><span>Delete</span></a></li>
                                {% endif %}
                            </ul>
                        </div>

                        <p>{{blog_obj.content|safe}}</p>
                    </div>

                    <div class="article-footer">
                        <div class="comments-area">
                            <h3 class="comments-title">{{blog_obj.num_comments}} Comments:</h3>

                            <ol class="comment-list">
                                {% for comment in blog_obj.blogcomment_set.all %}
                                <li class="comment">
                                    <div class="comment-body">
                                        <footer class="comment-meta">
                                            <div class="comment-author vcard">
                                                <img src="{{comment.user.avater.url}}" class="avatar" alt="image">
                                                <b class="fn">{{comment.user.user}}</b>
                                                <span class="says">says:</span>
                                            </div>

                                            <div class="comment-metadata">
                                                <a href="#">
                                                    <span>{{comment.created}}</span>
                                                </a>
                                            </div>

                                            {% ifequal request.user comment.user.user%}
                                        <ul class="blog-edit">
                                            <li>
                                                <a href="{% url 'blog:update_comment' comment.id blog_obj.id %}"><span
                                                        class="material-icons edit">create </span></a>
                                            </li>
                                            <li>
                                                <a href="{% url 'blog:delete_comment' comment.id blog_obj.id %}"><span
                                                        class="material-icons delete">delete </span></a>
                                            </li>
                                        </ul>
                                {% endifequal %}

                                </footer>

                                <div class="comment-content">
                                    <p>{{comment.body}}</p>
                                </div>
                        </div>
                        </li>
                        {% endfor %}
                        </ol>

                        <div class="comment-respond">
                            <h3 class="comment-reply-title">Leave a Comment</h3>

                            <form action="" class="comment-form" method='POST'>
                                <p class="comment-form-comment">
                                    
                                    {% csrf_token %}
                                    {{comment_form}}
                                </p>
                                <input type="hidden" name='blog_id' value={{blog_obj.id}}>
                                <button type="submit" name='comment_submit_form' class="box-btn mt-3">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-12">
            <aside class="widget-area" id="secondary">
                <section class="widget widget-peru-posts-thumb">
                    <h3 class="widget-title">Blog Read By:</h3>
                    <div class="post-wrap">
                        {% for reader in blog_obj.read.all %}
                        <article class="item">
                            <a href="/" class="thumb">
                                <img src="{{reader.user.profile.avater.url}}" alt="avater">
                            </a>
                            <div class="info">
                                <time datetime="2020-06-30">{{reader.created}}</time>
                                <h4 class="title usmall">
                                    <a href="">
                                        {{reader.user}}
                                    </a>
                                </h4>
                            </div>

                            <div class="clear"></div>
                        </article>
                        {% endfor %}
                    </div>
                    <hr>
                    <h3 class="widget-title">Recent Posts</h3>
                    <div class="post-wrap">
                        {% for recent in recent_posts %}
                            <article class="item">
                                <a href="{% url 'posts:postsDetails' recent.id %}" class="thumb blog">
                                    <span class="fullimage cover bg1" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall">
                                        <a href="{% url 'posts:postsDetails' recent.id %}">
                                            {{recent.heading|slice:50}}..
                                        </a>
                                    </h4>
                                    <time>{{recent.created|date}}</time>
                                </div>
                                <div class="clear"></div>
                            </article>
                        {% endfor %}
                    </div>
                </section>
            </aside>
        </div>
    </div>
    </div>
</section>
<!-- End Blog Details Area -->
{% include "home/footer.html" %}

{% endblock content %}

blog/templates/blog/blog.html
{% extends 'home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-banner-area ">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12 text-center">
                        <div class="banner-tittle">
                            <h1>
                                Blog
                            </h1>
                        </div>
                        <ul class="head-list">
                            <li>
                                <a href="/">
                                    Home
                                </a>
                            </li>
                            <li>Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="home-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="widget widget_search mb-5">
                    <div class="post-wrap">
                        <form class="search-form" method="GET" action="{% url 'blog:blog_search' %}" >
                            <label>
                                <input type="search" class="search-field" placeholder="Search by title or category" name="query" id="query">
                            </label>
                            <button type="submit"><i class="bx bx-search"></i></button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <a class="box-btn float-right" href="{% url 'blog:create_blog' %}">Create Blog</a>
            </div>
        </div>
        <div class="row">
            {% for blog  in blog_obj %}
            <div class="col-lg-4 col-md-6">
                <div class="single-blog">
                    <div class="content">
                        <a href="{% url 'blog:single_blog' blog.pk  %}">
                            <h3>{{blog.title|slice:50}}...</h3>
                        </a>
                        <ul>
                            <li>
                                <span>On: {{blog.created|date}}</span>
                            </li>
                            <li>
                                <a href="">By: {{blog.author.user}}</span></a>
                            </li>

                        </ul>

                        <ul class="mt-2">
                            <li>
                                <span><i class='bx bx-low-vision'></i>{{blog.read.all.count}} views</span>
                            </li>
                            <li>
                                <span><i class='bx bx-comment'></i>{{blog.num_comments}} comments</span>
                            </li>
                        </ul>

                        <span class="catagory">{{blog.category}}</span>

                        <form action="{% url 'blog:single_blog' blog.pk  %}" id='{{blog.id}}' method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="read_more" value="{{blog.id}}">
                            <button class="box-btn" type="submit">Read More</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include "home/footer.html" %}

{% endblock content %}

blog/templates/blog/update_comment.html
{% extends 'home/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-banner-area ">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12 text-center">
                        <div class="banner-tittle">
                            <h1>
                                Blog
                            </h1>
                        </div>
                        <ul class="head-list">
                            <li>
                                <a href="/">
                                    Home
                                </a>
                            </li>
                            <li>Edit Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Start Blog Details Area -->
<div class="container">
    <div class='row'>
        <div class="col-12 ptb-50m">
            <div class="edit-comment">
                <h3>Edit Comment</h3>
                <form action="" method="POST" >
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success mt-4">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Blog Details Area -->
{% include "home/footer.html" %}

{% endblock content %}