Ground/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from home import views
from django.contrib.auth import views as auth_views

admin.site.site_header='Ground Admin'
admin.site.site_title='Ground Admin'
admin.site.index_title='Ground Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home_url"),
    path('privecy/',views.privecy,name="privecy"),
    path('terms_condition/',views.terms_condition,name="terms_condition"),
    path('developer/',views.developer,name="developer"),
    path('blog/',include('blog.urls',namespace='blog')),
    path('feedback/',views.feedback,name='feedback'),
    path('pastebin/',include('pastebin.urls',namespace='pastebin')),
    path('user/',include('users.urls',namespace='users')),
    path('posts/',include('posts.urls',namespace='posts')),
    
    

    path('search/',views.user_search,name='user_search'),


    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name="users/passwordReset.html"),
        name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="users/passwordResetSent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="users/passwordResetForm.html"),
        name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="users/passwordResetDone.html"),
        name="password_reset_complete"),

    path('archive/',include('archive.urls',namespace='archive')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from .import views

app_name='blog'

urlpatterns = [
    path('main/',views.blog,name="all_blog"),
    path('blog-details/<pk>/',views.blog_details,name="single_blog"),
    path('create_blog/',views.create_blog,name="create_blog"),
    path('delete_blog/<pk>/',views.delete_blog,name='delete_blog'),
    path('update_blog/<pk>/',views.update_blog,name='update_blog'),

    path('delete_comment/<pk>/<postid>/',views.delete_comment,name='delete_comment'),
    path('update_comment/<pk>/<postid>/',views.update_comment,name='update_comment'),

    path('search/',views.blog_search,name='blog_search')
]

posts/urls.py
from django.urls import path
from .import views

app_name = 'posts'

urlpatterns = [
    path('allposts/',views.list_all_post_comments,name='allposts'),
    path('like/',views.like_comment_post,name='postsLike'),
    path('unlike/',views.Unlike_comment_post,name='postsUnlike'),
    path('delete/<pk>/',views.PostDelete,name='postsDelete'),
    path('update/<pk>/',views.PostUpdate,name='postsUpdate'),
    path('details/<pk>',views.PostDetails,name='postsDetails'),
    path('delete/<pk>/<postid>/',views.commentDelete,name='commentDelete'),
    path('edit/<pk>/<postid>/',views.commentEdit,name='commentEdit'), 
    path('search/',views.search_post,name='search_post'),  
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'users'

urlpatterns =[
    path('profile/<profileId>/',views.profile,name='profile'),
    path('signup/',views.signup,name='signup'),
    # path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('changepass',views.changepass,name='changepass'),
    path('activate/<uidb64>/<token>/',views.activate,name='activate'),

    # path('reset_password/',
    #     auth_views.PasswordResetView.as_view(),
    #     name="reset_password"),

    # path('reset_password_sent/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done"),

    # path('reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm"),

    # path('reset_password_complete/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete"),
]

posts/forms.py
from django import forms
from .models import Post,Comment


class PostModelForm(forms.ModelForm):
    heading = forms.CharField(label='',widget=forms.Textarea(attrs={'class':'form-control heading-form','rows':'1','placeholder':'Heading...'}))
    link = forms.CharField(required=False,label='',widget=forms.Textarea(attrs={'class':'form-control link-form','rows':'3','placeholder':'Your Problem Link'}))
    content = forms.CharField(label='',widget=forms.Textarea(attrs={'rows':'3','placeholder':'What is on your mind...'}))
    image = forms.ImageField(required=False,label='',widget=forms.FileInput(attrs={'class':'file-upload-field','id':'actual-btn'}))
    class Meta:
        model = Post
        fields = ['heading','link','content','image']


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class':'form-control commentText','placeholder':'Write a comment'}),
    )
    class Meta:
        model = Comment
        fields = ['body',]

posts/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.http import Http404
from .models import Post,Like,Comment,Unlike
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from users.forms import LoginForm
from users.models import Profile
from .forms import PostModelForm,CommentModelForm
from django.views.generic import UpdateView,DeleteView
from django.urls import reverse_lazy ,reverse
from django.contrib.auth.models import User
from home.models import Feedback
from django.db.models import Q
from blog.models import Blog

# Create your views here.

def list_all_post_comments(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            all_posts = Post.objects.all()
            all_blogs = Blog.objects.all()
            profile = Profile.objects.get(user=request.user)

            # Post form, Comment form 
            post_form = PostModelForm()
            comment_form = CommentModelForm()
            
            if 'post_submit_form' in request.POST:
                post_form = PostModelForm(request.POST or None,request.FILES or None)
                if post_form.is_valid():
                    instance =  post_form.save(commit=False)
                    instance.author = profile
                    instance.save()
            if 'comment_submit_form' in request.POST:
                comment_form = CommentModelForm(request.POST or None)
                if comment_form.is_valid():
                    instance = comment_form.save(commit=False)
                    instance.user = profile
                    instance.post = Post.objects.get(id = request.POST.get('post_id'))
                    instance.save()

            post_form = PostModelForm()
            comment_form = CommentModelForm()


            total_post_num = all_posts.count()
            total_blog_num = all_blogs.count()
            total_user_num = User.objects.all().count()
            total_feedback_num = Feedback.objects.all().count()

            context={
                'all_posts':all_posts,
                'profile':profile,
                'post_form':post_form,
                'comment_form':comment_form,
                'total_post':total_post_num,
                'total_blog':total_blog_num,
                'total_user':total_user_num,
                'total_feedback':total_feedback_num,
                'active':'active',
            }
            return render(request,'posts/listPost.html',context)
        else:
            return HttpResponseRedirect('/user/login')
    else:
        all_posts = Post.objects.all()
        all_blogs = Blog.objects.all()
        recent_blogs = Blog.objects.all()[:10]
        post_form = PostModelForm()
        comment_form = CommentModelForm()


        total_post_num = all_posts.count()
        total_blog_num = all_blogs.count()
        total_user_num = User.objects.all().count()
        total_feedback_num = Feedback.objects.all().count()
        context={
            'all_posts':all_posts,
            'recent_blogs':recent_blogs,
            'post_form':post_form,
            'comment_form':comment_form,
            'total_post':total_post_num,
            'total_blog':total_blog_num,
            'total_user':total_user_num,
            'total_feedback':total_feedback_num,
            'active':'active',
        }
        return render(request,'posts/listPost.html',context)



def like_comment_post(request):
    if request.user.is_authenticated:
        currentUser = request.user
        if request.method == 'POST':
            postId = request.POST.get('post_id')
            postObj = Post.objects.get(id=postId)
            profileObj = Profile.objects.get(user=currentUser)

            if profileObj in postObj.liked.all():
                postObj.liked.remove(profileObj)
            else:
                postObj.liked.add(profileObj)
                if profileObj in postObj.unliked.all():
                    postObj.unliked.remove(profileObj)
                    unlike = Unlike.objects.get(user=profileObj,post_id=postId)
                    unlike.value = 'Undo'
                    unlike.save()
                    

            like, created = Like.objects.get_or_create(user=profileObj,post_id=postId)
            if not created:
                #print(1111)
                if like.value == 'Like':
                    #print(222)
                    like.value = 'Undo' #////////////////////////
                   # print(like.value)
                else:
                    #print(3333)
                    like.value = 'Like'
            else:
               # print(4444)
                like.value = 'Like'
                
            postObj.save()
            like.save()
        return redirect('posts:allposts')
    
    else:
        return HttpResponseRedirect('/user/login/')

def Unlike_comment_post(request):
    if request.user.is_authenticated:
        currentUser = request.user
        if request.method == 'POST':
            postId = request.POST.get('post_id')
            postObj = Post.objects.get(id=postId)
            profileObj = Profile.objects.get(user=currentUser)

            if profileObj in postObj.unliked.all():
                postObj.unliked.remove(profileObj)
            else:
                postObj.unliked.add(profileObj)
                if profileObj in postObj.liked.all():
                    postObj.liked.remove(profileObj)
                    like = Like.objects.get(user=profileObj,post_id=postId)
                    like.value='Undo'
                    like.save()

            unlike, created = Unlike.objects.get_or_create(user=profileObj,post_id=postId)
            if not created:
                if unlike.value == 'Unlike':
                    unlike.value = 'Undo'
                else:
                    unlike.value = 'Unlike'
            else:
                unlike.value = 'Unlike'
                
            postObj.save()
            unlike.save()
        return redirect('posts:allposts')
    
    else:
        return HttpResponseRedirect('/user/login/')



def PostDelete(request,pk):
    if request.user.is_authenticated:
        try:
            obj = Post.objects.get(pk=pk)
            if obj.author.user == request.user:
                obj.delete()
                return redirect('posts:allposts')
            else:
                return redirect('posts:allposts')
        except Post.DoesNotExist:
            raise Http404("Your link is Wrong or it is not available.Here") 
    else:
        return redirect('users:login')


def PostUpdate(request,pk):
    if request.user.is_authenticated:
        if request.method == 'POST':
            try:
                obj = Post.objects.get(pk=pk)
                if obj.author.user == request.user:
                    form = PostModelForm(request.POST,instance=obj)
                    if form.is_valid():
                        form.save()
                        obj = form.save()
                        obj.save()
                        context = {
                            'form':form,
                            'active':'active',
                        }
                        return redirect(reverse('posts:postsDetails',args=pk))
                else:
                    return redirect('posts:allposts')
            except Post.DoesNotExist:
                raise Http404("Your link is Wrong or it is not available.Here")

        else:
            try:
                obj = Post.objects.get(pk=pk)
                if obj.author.user == request.user:
                    form = PostModelForm(instance=obj)
                    context = {
                        'form':form,
                        'active':'active',
                    }
                    return render(request,'posts/update.html',context)
                else:
                    return redirect('posts:allposts')
            except Post.DoesNotExist:
                raise Http404("Your link is Wrong or it is not available.Here") 
    else:
        return redirect('users:login')


def PostDetails(request,pk):
    if request.method == 'POST':
        if request.user.is_authenticated:
            if 'comment_submit_form' in request.POST:
                comment_form = CommentModelForm(request.POST or None)
                profile = Profile.objects.get(user=request.user)
                if comment_form.is_valid():
                    instance = comment_form.save(commit=False)
                    instance.user = profile
                    instance.post = Post.objects.get(id = request.POST.get('post_id'))
                    instance.save()
                    obj = Post.objects.get(pk=pk)
                    comment_form = CommentModelForm()
                    context = {
                        'post':obj,
                        'comment_form':comment_form,
                        'active':'active',
                    }
                    return render(request,'posts/post_details.html',context)
        else:
            return redirect('users:login')
    else:
        obj = Post.objects.get(pk=pk)
        comment_form = CommentModelForm()
        context = {
            'post':obj,
            'comment_form':comment_form,
            'active':'active',
        }
        return render(request,'posts/post_details.html',context)



#///////////////////////////  Comment section ////////////////////////////////////



def commentEdit(request,pk,postid):
    if request.user.is_authenticated:
        if request.method == 'POST':
            try:
                obj = Comment.objects.get(pk=pk)
                if obj.user.user == request.user:
                    form = CommentModelForm(request.POST,instance=obj)
                    if form.is_valid():
                        form.save()
                        obj = form.save()
                        obj.save()
                        context = {
                            'form':form,

posts/templates/posts/commentEdit.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class='row'>
            <div class="col-12 ptb-50">
                <div class="edit-comment">
                    <h3>Edit Comment</h3>
                    <form action="" method="POST" >
                        {% csrf_token %}
                        {{form}}
                        <button type="submit" class="btn btn-success mt-4">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% include "home/footer.html" %}
{% endblock content %}

posts/templates/posts/post_details.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}

<div class="post-details-area">
    <div class="post-banner-area ">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-12">
                            <div class="banner-tittle">
                                <h1>
                                    {{post.heading}}
                                </h1>
                            </div>
                            <ul class="head-list">
                                <li>
                                    <a href="/">
                                        Home
                                    </a>
                                </li>
                                <li>{{post.heading}}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-10 m-auto col-md-8 ptb-50m">
                <div class="home-post-area">
                    {% comment %} {% for post in all_posts %} {% endcomment %}
                    <div class="single-post">
                        <div class="row">
                            <div class="col-lg-6 col-md-6">
                                <div class="profile d-flex">
                                    <img src="{{post.author.avater.url}}" alt="demo">
                                    <ul class="user-details">
                                        <li>
                                            <a class="username" href="{% url 'users:profile' post.author.user.profile.id %}">{{ post.author.user }}</a>
                                        </li>
                                        <li>
                                            <p>{{ post.created|timesince}} ago</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6 text-right">
                                {% ifequal request.user post.author.user %}
                                <div class="post-menu">
                                    <a class="postbtn bx bx-dots-vertical-rounded"></a>
                                    <div class="menu-content">
                                        <a href="{% url 'posts:postsUpdate' post.pk %}">Edit</a>
                                        <a href="{% url 'posts:postsDelete' post.pk %}">Delete</a>
                                        <a href="#">Hide</a>
                                    </div>
                                </div>
                                {% endifequal %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-12">
                                <div class="post-content">
                                   <a class="post-content-head" href="{% url 'posts:postsDetails' post.pk %}"><h2>{{post.heading}}</h2></a>
                                    {% if post.link %}
                                    <p class="p-link">Problem Link: <a target="_blank"
                                            href="{{post.link}}">{{post.link}}</a></p>
                                    {% endif %}
                                    <p class="show-read-more">{{post.content|capfirst }}</p>
                                    {% if post.image %}
                                    <div>
                                        <img src="{{post.image.url}}" alt="post-img">
                                    </div>
                                    {% endif %}

                                </div>

                                <!--Like  Comments-->
                                <div class="like-comment">
                                    <div class="like">
                                        <form class='like-form' id='{{post.id}}' action="{% url 'posts:postsLike' %}"
                                            method="POST" enctype=multipart/form-data>
                                            {% csrf_token %}
                                            <input type="hidden" name="post_id" value={{post.id}}>

                                            <button type="submit" href="javascript:void(0);"
                                                class="like-button{{post.id}}">
                                                {% if request.user.profile not in post.liked.all %}
                                                <span class="material-icons">thumb_up</span>
                                                {% else %}
                                                <span class="material-icons">thumb_down</span>
                                                {% endif %}
                                            </button>
                                            <span class="like-count{{post.id}}">{{post.num_likes}}</span>
                                        </form>
                                    </div>
                                    <div class="comment">
                                        <a href=""><i class='bx bxs-comment-dots'></i></a>
                                         <span class="comment-count">{{post.num_comments}} Comments</span>
                                    </div>
                                </div>

                                <div class="comments">
                                    {% if not post.comment_set.all %}
                                    {% else %}
                                    {% for comment in post.comment_set.all %}
                                    <div class="single-comment">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="comment comment-box d-flex">

                                                    <img src="{{comment.user.avater.url}}" alt="demo">

                                                    <ul class="user-details">
                                                        <li>
                                                            <a class="username" href="#">{{comment.user.user}}</a>
                                                        </li>
                                                        <li>
                                                            <p>{{comment.created}}</p>
                                                        </li>
                                                    </ul>

                                                    <!-- Comment edit delete -->

                                                    <ul class="comment-edit">
                                                        {% ifequal request.user comment.user.user%}
                                                            <li>
                                                                <a href="{% url 'posts:commentEdit' comment.id post.id %}"><span class="material-icons edit">create </span></a>
                                                            </li>
                                                            <li>
                                                                <a href="{% url 'posts:commentDelete' comment.id post.id %}"><span class="material-icons delete">delete </span></a>
                                                            </li>
                                                        {% endifequal %}
                                                    </ul>
                                                </div>
                                                <p class="comment-body">{{comment.body|capfirst }}</p>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    {% endif %}
                                </div>

                                <div class="comment-field">
                                    <h3 class="comment-heading">Leave a comment</h3>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        {{comment_form}}
                                        {% if request.user.is_authenticated %}
                                        {% endif %}
                                        <input type="hidden" name='post_id' value={{post.id}}>
                                        <button type="submit" class="box-btn mt-3" name="comment_submit_form">Submit</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% comment %} {% endfor %} {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include "home/footer.html" %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class='row'>
        <div class="col-lg-6 col-md-6 ptb-50 m-auto">
            <h3>Update Post</h3>
            <form action="" method="POST" enctype=multipart/form-data>
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">Update</button>
            </form>
        </div>
    </div>
</div>
{% include "home/footer.html" %}
{% endblock content %}